2024-09-04 13:04:38,419 ERROR frappe Failed to run after request hook
Site: view.local
Form Dict: {'doctype': 'Module Def', 'with_parent': '1', 'cached_timestamp': ''}
Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 2286, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 90, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 60, in _get_controller
    module_name, custom = frappe.db.get_value(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: -6178526756365427493

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/defaults.py", line 242, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")
2024-09-04 13:04:56,125 ERROR frappe Failed to run after request hook
Site: view.local
Form Dict: {}
Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 2286, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 90, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 60, in _get_controller
    module_name, custom = frappe.db.get_value(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: -6178526756365427493

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/defaults.py", line 242, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")
2024-09-04 13:05:32,909 ERROR frappe Failed to run after request hook
Site: view.local
Form Dict: {}
Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 2286, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 90, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 60, in _get_controller
    module_name, custom = frappe.db.get_value(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: -4916841611399300196

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/defaults.py", line 242, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")
2024-09-04 13:05:37,529 ERROR frappe Failed to run after request hook
Site: view.local
Form Dict: {}
Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 2286, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 90, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 60, in _get_controller
    module_name, custom = frappe.db.get_value(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: -4916841611399300196

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/defaults.py", line 242, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")
2024-09-04 13:06:11,579 ERROR frappe Failed to run after request hook
Site: view.local
Form Dict: {}
Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 2286, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 90, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 60, in _get_controller
    module_name, custom = frappe.db.get_value(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 2739326282550270525

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/defaults.py", line 242, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")
2024-09-04 13:06:15,213 ERROR frappe Failed to run after request hook
Site: view.local
Form Dict: {}
Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 2286, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 90, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/model/base_document.py", line 60, in _get_controller
    module_name, custom = frappe.db.get_value(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 2739326282550270525

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/defaults.py", line 242, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tatyanaamugo/trial/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'view'@'localhost' (using password: YES)")
